<script setup lang="ts">
import { computed, ref } from 'vue'
import { ElMessage } from 'element-plus'
import PlatformHeader from '@/components/platform/PlatformHeader.vue'
const keyword=ref(''); const category=ref('全部'); const categories=['全部','图片','图标','视频'];
const assets=ref([{name:'夏日主视觉',type:'图片',size:'245 KB'},{name:'商品防晒霜',type:'图片',size:'86 KB'},{name:'粉色耳机',type:'图片',size:'73 KB'},{name:'营销图标集',type:'图标',size:'32 KB'},{name:'品牌宣传视频',type:'视频',size:'8.4 MB'}]);
const filtered=computed(()=>assets.value.filter(a=>(category.value==='全部'||a.type===category.value)&&a.name.includes(keyword.value.trim())));
function upload(){ElMessage.success('已添加到素材库（演示）')}
</script>
<template><div class="shell"><PlatformHeader/><main class="page"><div class="title"><div><h1>素材管理</h1><p>统一管理营销页面使用的图片、图标和视频素材</p></div><button @click="upload"><i class="i-tabler-upload"/> 上传素材</button></div><section class="panel"><div class="toolbar"><div class="tabs"><button v-for="c in categories" :class="{active:category===c}" @click="category=c">{{c}}</button></div><div class="search"><i class="i-tabler-search"/><input v-model="keyword" placeholder="搜索素材"/></div></div><div class="grid"><article v-for="item in filtered" :key="item.name"><div class="preview" :class="item.type"><i :class="item.type==='视频'?'i-tabler-player-play-filled':item.type==='图标'?'i-tabler-icons':'i-tabler-photo'"/></div><div class="meta"><strong>{{item.name}}</strong><span>{{item.type}} · {{item.size}}</span></div><button class="more">•••</button></article><button class="upload-card" @click="upload"><i class="i-tabler-cloud-upload"/><strong>上传新素材</strong><span>支持 JPG、PNG、SVG、MP4</span></button></div></section></main></div></template>
<style scoped>.shell{min-height:100%;background:#f6f8fc}.page{max-width:1380px;margin:auto;padding:30px 32px}.title{display:flex;justify-content:space-between;align-items:center;margin-bottom:20px}.title h1{font-size:24px;margin:0 0 6px;color:#1f2f44}.title p{margin:0;color:#8b98aa;font-size:12px}.title>button{height:38px;border:0;border-radius:9px;background:#2868ff;color:#fff;padding:0 16px}.panel{background:#fff;border:1px solid #e8edf4;border-radius:15px;padding:20px}.toolbar{display:flex;justify-content:space-between;margin-bottom:18px}.tabs{display:flex;gap:6px}.tabs button{border:0;background:#f5f7fb;padding:8px 14px;border-radius:8px;color:#708095}.tabs .active{background:#edf4ff;color:#2868ff}.search{width:220px;height:34px;border:1px solid #e3e9f1;border-radius:8px;display:flex;align-items:center;padding:0 10px;color:#99a6b7}.search input{border:0;outline:0;width:100%;margin-left:6px}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.grid article,.upload-card{border:1px solid #e8edf4;border-radius:12px;overflow:hidden;background:#fff;position:relative}.preview{height:150px;display:grid;place-items:center;font-size:34px;color:white;background:linear-gradient(145deg,#73c7ff,#b8efe1)}.preview.图标{background:linear-gradient(145deg,#9f8cff,#d8ceff)}.preview.视频{background:linear-gradient(145deg,#ff9a84,#ffd1b7)}.meta{padding:12px;display:flex;flex-direction:column}.meta strong{font-size:13px;color:#344357}.meta span{font-size:10px;color:#99a5b4;margin-top:4px}.more{position:absolute;right:8px;bottom:13px;border:0;background:transparent;color:#8d99a9}.upload-card{min-height:206px;border-style:dashed;display:flex;flex-direction:column;align-items:center;justify-content:center;color:#8d9aaa}.upload-card i{font-size:30px;color:#3674ff}.upload-card strong{margin-top:8px;font-size:13px}.upload-card span{font-size:10px;margin-top:4px}@media(max-width:1100px){.grid{grid-template-columns:repeat(2,1fr)}}</style>